import Head from 'next/head'
import VanillaJS from '../components/vanilla-js/vanilla-js'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Teenternz</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <VanillaJS />
        
      </div>

    </>
  )
}
